/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermera;

import java.awt.event.ActionListener;

/**
 *
 * @author Zakaria
 */
public class EnfermeraVista extends javax.swing.JFrame {

    /**
     * Creates new form EnfermeraVista
     */
    public EnfermeraVista() {

        initComponents();

        inventarioMedicamentos.setActionCommand("enfermeraInventario");
        b_buscar_medicamentos1.setActionCommand("enfermeraBuscar");
        administrarMedicamentos.setActionCommand("enfermeraAdministrar");
        b_cerrar.setActionCommand("enfermeraCerrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_salir = new javax.swing.JLabel();
        b_cerrar = new java.awt.Button();
        inventarioMedicamentos = new java.awt.Button();
        administrarMedicamentos = new java.awt.Button();
        b_buscar_medicamentos1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 35, 35));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        l_salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_salir.setForeground(new java.awt.Color(57, 113, 177));
        l_salir.setText("X");

        b_cerrar.setBackground(new java.awt.Color(126, 87, 194));
        b_cerrar.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        b_cerrar.setLabel("Cerrar");

        inventarioMedicamentos.setBackground(new java.awt.Color(126, 87, 194));
        inventarioMedicamentos.setFont(new java.awt.Font("Century Gothic", 0, 12));
        inventarioMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        inventarioMedicamentos.setLabel("Administrar Inventario");
        inventarioMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioMedicamentosActionPerformed(evt);
            }
        });

        administrarMedicamentos.setBackground(new java.awt.Color(126, 87, 194));
        administrarMedicamentos.setFont(new java.awt.Font("Century Gothic", 0, 12));
        administrarMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        administrarMedicamentos.setLabel("Administrar Medicamentos");
        administrarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarMedicamentosActionPerformed(evt);
            }
        });

        b_buscar_medicamentos1.setBackground(new java.awt.Color(126, 87, 194));
        b_buscar_medicamentos1.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_buscar_medicamentos1.setForeground(new java.awt.Color(255, 255, 255));
        b_buscar_medicamentos1.setLabel("Buscar Medicamentos");
        b_buscar_medicamentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscar_medicamentos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(l_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(inventarioMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(b_buscar_medicamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(administrarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(b_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(l_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(inventarioMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(b_buscar_medicamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(administrarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(b_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventarioMedicamentosActionPerformed

    private void administrarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_administrarMedicamentosActionPerformed

    private void b_buscar_medicamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscar_medicamentos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_buscar_medicamentos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnfermeraVista().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button administrarMedicamentos;
    private java.awt.Button b_buscar_medicamentos1;
    private java.awt.Button b_cerrar;
    private java.awt.Button inventarioMedicamentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_salir;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener actionListener) {

        inventarioMedicamentos.addActionListener(actionListener);
        administrarMedicamentos.addActionListener(actionListener);
        b_buscar_medicamentos1.addActionListener(actionListener);
        b_cerrar.addActionListener(actionListener);

    }

}
